# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

buildA_kerr_cpp <- function(s, d, w, v) {
    .Call(`_AGHmatrix_buildA_kerr_cpp`, s, d, w, v)
}

buildA_ploidy2_cpp <- function(sire, dire, n) {
    .Call(`_AGHmatrix_buildA_ploidy2_cpp`, sire, dire, n)
}

buildA_slater_cpp <- function(s, d, w) {
    .Call(`_AGHmatrix_buildA_slater_cpp`, s, d, w)
}

buildDominanceMatrix_cpp <- function(A, s, d) {
    .Call(`_AGHmatrix_buildDominanceMatrix_cpp`, A, s, d)
}

Gmatrix_Endelman <- function(M, ploidy) {
    .Call(`_AGHmatrix_Gmatrix_Endelman`, M, ploidy)
}

Gmatrix_general_weighted <- function(Z, weights, K) {
    .Call(`_AGHmatrix_Gmatrix_general_weighted`, Z, weights, K)
}

Gmatrix_MarkersMask <- function(M) {
    .Call(`_AGHmatrix_Gmatrix_MarkersMask`, M)
}

Gmatrix_Slater <- function(M, Frequency, FreqP, NumberMarkers) {
    .Call(`_AGHmatrix_Gmatrix_Slater`, M, Frequency, FreqP, NumberMarkers)
}

Gmatrix_Su <- function(M) {
    .Call(`_AGHmatrix_Gmatrix_Su`, M)
}

Gmatrix_unweighted <- function(Z, K) {
    .Call(`_AGHmatrix_Gmatrix_unweighted`, Z, K)
}

Gmatrix_vanraden <- function(M, FreqP, denom) {
    .Call(`_AGHmatrix_Gmatrix_vanraden`, M, FreqP, denom)
}

Gmatrix_VanRaden_weighted <- function(M, weights, FreqP, denom) {
    .Call(`_AGHmatrix_Gmatrix_VanRaden_weighted`, M, weights, FreqP, denom)
}

Gmatrix_Vitezica <- function(M, FreqP) {
    .Call(`_AGHmatrix_Gmatrix_Vitezica`, M, FreqP)
}

preprocessSNPmatrix <- function(mat, missingValue) {
    .Call(`_AGHmatrix_preprocessSNPmatrix`, mat, missingValue)
}

